apiVersion: v1
data:
  cpu-usage.rules: |
    groups:
    - name: NodeCPUUsage
      rules:
      - alert: NodeCPUUsage-High
        expr: (100 - (avg by (instance) (irate(node_cpu{mode="idle"}[1m])) * 100)) > 10
        for: 10s
        labels:
          severity: "page"
        annotations:
          summary: "{{$labels.instance}}: High CPU usage detected"
          description: "{{$labels.instance}}: CPU usage is above 50% (current value is: {{ $value }})"
  instance-availability.rules: |
    groups:
    - name: InstanceDown
      rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: "page"
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
  low-disk-space.rules: |
    groups:
    - name: NodeLowRootDisk
      rules:
      - alert: NodeLowRootDisk
        expr: ((node_filesystem_size{mountpoint="/root-disk"} - node_filesystem_free{mountpoint="/root-disk"} ) / node_filesystem_size{mountpoint="/root-disk"} * 100) > 75
        for: 5m
        labels:
          severity: "page"
        annotations:
          summary: "{{$labels.instance}}: Low root disk space"
          description: "{{$labels.instance}}: Root disk usage is above 75% (current value is: {{ $value }})"

    - name: NodeLowDataDisk
      rules:
      - alert: NodeLowDataDisk
        expr: ((node_filesystem_size{mountpoint="/data-disk"} - node_filesystem_free{mountpoint="/data-disk"} ) / node_filesystem_size{mountpoint="/data-disk"} * 100) > 75
        for: 5m
        labels:
          severity: "page"
        annotations:
          summary: "{{$labels.instance}}: Low data disk space"
          description: "{{$labels.instance}}: Data disk usage is above 75% (current value is: {{ $value }})"
  mem-usage.rules: |
    groups:
    - name: NodeSwapUsage
      rules:
      - alert: NodeSwapUsage
        expr: (((node_memory_SwapTotal-node_memory_SwapFree)/node_memory_SwapTotal)*100) > 75
        for: 5m
        labels:
          severity: "page"
        annotations:
          summary: "{{$labels.instance}}: Swap usage detected"
          description: "{{$labels.instance}}: Swap usage usage is above 75% (current value is: {{ $value }})"

    - name: NodeMemoryUsage
      rules:
      - alert: NodeMemoryUsage
        expr: (((node_memory_MemTotal-node_memory_MemFree-node_memory_Cached)/(node_memory_MemTotal)*100)) > 75
        for: 5m
        labels:
          severity: "page"
        annotations:
          summary: "{{$labels.instance}}: High memory usage detected"
          description: "{{$labels.instance}}: Memory usage is above 75% (current value is: {{ $value }})"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-rules
  namespace: monitoring
