groups:
- name: cpu-usage.rules
  rules:
  - alert: high_cpu_usage 
    expr: (100 - (avg by(instance) (irate(node_cpu{mode="idle",job="node"}[1m]))
      * 100)) > 40
    for: 10s
    labels:
      severity: moderate 
    annotations:
      DESCRIPTION: '{{$labels.instance}}: CPU usage is above 40% (current value is:
        {{ $value }})'
      SUMMARY: '{{$labels.instance}}: High CPU usage detected'
